version: "3.3"

services:
  aioweb:
    build:
      context: .
      dockerfile: Dockerfile
    image: aioweb
    command: ['python', 'app.py']
    ports:
      - "8080:8080"
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
